import axios from "axios"

function BaseDados () {

    const apiURLusuarios    = "https://ironrest.herokuapp.com/mUsuarios";
    const apiURLunidades    = "https://ironrest.herokuapp.com/mUnidades";
    const apiURLhistoricos  = "https://ironrest.herokuapp.com/mHistoricos";
    const apiURLcontas      = "https://ironrest.herokuapp.com/mContas";
    const apiURLlancamentos = "https://ironrest.herokuapp.com/mLancamentos";
    const apiURLsdAno       = "https://ironrest.herokuapp.com/mSDano";
    const apiURLsdMes       = "https://ironrest.herokuapp.com/mSDmes";
    const apiURLsdDia       = "https://ironrest.herokuapp.com/mSDdia";

    const handleDeleta = async (api) => {
        try {
            await axios.delete(api)
            } catch (error) { console.log(error) 
        }
    }    
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mUsuarios")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mUnidades")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mHistoricos")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mContas")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mLancamentos")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mSDano")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mSDmes")
    handleDeleta("https://ironrest.herokuapp.com/deleteCollection/mSDdia")

    const handleInclusao = async (api, form) => {
        try {
            await axios.post(api, form)
            } catch (error) { console.log(error) 
        }
    }    
    handleInclusao(apiURLusuarios,    {permissao: "Administrativa", codigo: "1", descricao: "Mario", unidades: "1,2,3,4,5", senha: "12345"} )
    handleInclusao(apiURLusuarios,    {permissao: "Administrativa", codigo: "2", descricao: "Marcia", unidades: "1,2,3,4,5", senha: "12345"} )
    handleInclusao(apiURLusuarios,    {permissao: "Comum", codigo: "3", descricao: "Carlos", unidades: "1,2,3,4,5", senha: "12345"} )
    handleInclusao(apiURLusuarios,    {permissao: "Comum", codigo: "4", descricao: "Andre", unidades: "1,2,3,4,5", senha: "12345"} )
    handleInclusao(apiURLusuarios,    {permissao: "Comum", codigo: "5", descricao: "Pedro", unidades: "1,2,3,4,5", senha: "12345"} )

    handleInclusao(apiURLunidades,    {codigo: "1", descricao: "Caxias - RS"} )
    handleInclusao(apiURLunidades,    {codigo: "2", descricao: "Castro - PR"} )
    handleInclusao(apiURLunidades,    {codigo: "3", descricao: "São Paulo - SP"} )
    handleInclusao(apiURLunidades,    {codigo: "4", descricao: "Blumenau - SC"} )
    handleInclusao(apiURLunidades,    {codigo: "5", descricao: "Rio de Janeiro - RJ"} )

    handleInclusao(apiURLhistoricos,  {codigo: "1",  unidade: "1", descricao: "CH Depositado"} )
    handleInclusao(apiURLhistoricos,  {codigo: "2",  unidade: "1", descricao: "Saque no Caixa"} )
    handleInclusao(apiURLhistoricos,  {codigo: "3",  unidade: "1", descricao: "Transferencia"} )
    handleInclusao(apiURLhistoricos,  {codigo: "4",  unidade: "1", descricao: "Despesa Bancaria"} )
    handleInclusao(apiURLhistoricos,  {codigo: "5",  unidade: "1", descricao: "Compra de Imovel"} )
    handleInclusao(apiURLhistoricos,  {codigo: "6",  unidade: "1", descricao: "Venda de Ativo Imobilizado"} )
    handleInclusao(apiURLhistoricos,  {codigo: "7",  unidade: "1", descricao: "Despesas de Produção"} )
    handleInclusao(apiURLhistoricos,  {codigo: "8",  unidade: "1", descricao: "Vendas a vista"} )
    handleInclusao(apiURLhistoricos,  {codigo: "9",  unidade: "1", descricao: "Vendas a prazo"} )
    handleInclusao(apiURLhistoricos,  {codigo: "10", unidade: "1", descricao: "Creditos a receber"} )

    handleInclusao(apiURLhistoricos,  {codigo: "1",  unidade: "2", descricao: "CH Depositado"} )
    handleInclusao(apiURLhistoricos,  {codigo: "4",  unidade: "2", descricao: "Saque no Caixa"} )
    handleInclusao(apiURLhistoricos,  {codigo: "8",  unidade: "2", descricao: "Transferencia"} )
    handleInclusao(apiURLhistoricos,  {codigo: "12", unidade: "2", descricao: "Despesa Bancaria"} )
    handleInclusao(apiURLhistoricos,  {codigo: "16", unidade: "2", descricao: "Compra de Imovel"} )
    handleInclusao(apiURLhistoricos,  {codigo: "18", unidade: "2", descricao: "Venda de Ativo Imobilizado"} )
    handleInclusao(apiURLhistoricos,  {codigo: "19", unidade: "2", descricao: "Despesas de Produção"} )
    handleInclusao(apiURLhistoricos,  {codigo: "20", unidade: "2", descricao: "Vendas a vista"} )
    handleInclusao(apiURLhistoricos,  {codigo: "35", unidade: "2", descricao: "Vendas a prazo"} )
    handleInclusao(apiURLhistoricos,  {codigo: "40", unidade: "2", descricao: "Creditos a receber"} )

    handleInclusao(apiURLcontas,{ estrutural: '100000000', unidade: '1', reduzido:'7909', nivel:'1', descricao:'ATIVO' })
    handleInclusao(apiURLcontas,{ estrutural: '110000000', unidade: '1', reduzido:'1342', nivel:'2', descricao:'ATIVO CIRCULANTE' })
    handleInclusao(apiURLcontas,{ estrutural: '111000000', unidade: '1', reduzido:'7544', nivel:'3', descricao:'DISPONÍVEL' })
    handleInclusao(apiURLcontas,{ estrutural: '111100000', unidade: '1', reduzido:'5880', nivel:'4', descricao:'Bens Numerários' })
    handleInclusao(apiURLcontas,{ estrutural: '111110000', unidade: '1', reduzido:'9793', nivel:'9', descricao:'Caixa - fundo fixo' })
    handleInclusao(apiURLcontas,{ estrutural: '111200000', unidade: '1', reduzido:'7942', nivel:'4', descricao:'Bancos Conta Movimento' })
    handleInclusao(apiURLcontas,{ estrutural: '111210000', unidade: '1', reduzido:'5590', nivel:'9', descricao:'Banco X S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '111220000', unidade: '1', reduzido:'2071', nivel:'9', descricao:'Banco Y S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '111230000', unidade: '1', reduzido:'9959', nivel:'9', descricao:'Banco Alfa S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '111300000', unidade: '1', reduzido:'9097', nivel:'4', descricao:'Aplicações Financeiras' })
    handleInclusao(apiURLcontas,{ estrutural: '111310000', unidade: '1', reduzido:'7979', nivel:'9', descricao:'Banco X S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '111320000', unidade: '1', reduzido:'7427', nivel:'9', descricao:'Banco Y S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '111330000', unidade: '1', reduzido:'9512', nivel:'9', descricao:'Banco Alfa S/A' })
    handleInclusao(apiURLcontas,{ estrutural: '112000000', unidade: '1', reduzido:'2942', nivel:'3', descricao:'CRÉDITOS' })
    handleInclusao(apiURLcontas,{ estrutural: '112100000', unidade: '1', reduzido:'5012', nivel:'4', descricao:'Clientes' })
    handleInclusao(apiURLcontas,{ estrutural: '112110000', unidade: '1', reduzido:'1507', nivel:'9', descricao:'Clientes nacionais' })
    handleInclusao(apiURLcontas,{ estrutural: '112120000', unidade: '1', reduzido:'7344', nivel:'9', descricao:'Clientes estrangeiros' })
    handleInclusao(apiURLcontas,{ estrutural: '112130000', unidade: '1', reduzido:'3075', nivel:'9', descricao:'(-) Perdas estimadas em crédito de liquidação duvidosa' })
    handleInclusao(apiURLcontas,{ estrutural: '112140000', unidade: '1', reduzido:'9301', nivel:'9', descricao:'(-) Ajuste a valor presente' })
    handleInclusao(apiURLcontas,{ estrutural: '112150000', unidade: '1', reduzido:'5201', nivel:'9', descricao:'Faturamento para entrega futura' })
    handleInclusao(apiURLcontas,{ estrutural: '112200000', unidade: '1', reduzido:'9224', nivel:'4', descricao:'Outros créditos' })
    handleInclusao(apiURLcontas,{ estrutural: '112210000', unidade: '1', reduzido:'5342', nivel:'9', descricao:'Contas a receber' })
    handleInclusao(apiURLcontas,{ estrutural: '112220000', unidade: '1', reduzido:'9133', nivel:'9', descricao:'Títulos a receber' })
    handleInclusao(apiURLcontas,{ estrutural: '112300000', unidade: '1', reduzido:'8352', nivel:'4', descricao:'Créditos de Funcionários' })
    handleInclusao(apiURLcontas,{ estrutural: '112320000', unidade: '1', reduzido:'5694', nivel:'9', descricao:'Adiantamento a funcionários' })
    handleInclusao(apiURLcontas,{ estrutural: '112320000', unidade: '1', reduzido:'6380', nivel:'9', descricao:'Empréstimos a funcionários' })
    handleInclusao(apiURLcontas,{ estrutural: '112330000', unidade: '1', reduzido:'6909', nivel:'9', descricao:'Adiantamento de férias' })
    handleInclusao(apiURLcontas,{ estrutural: '112400000', unidade: '1', reduzido:'4695', nivel:'4', descricao:'Impostos e Contribuições a Recuperar' }              )
    handleInclusao(apiURLcontas,{ estrutural: '112410000', unidade: '1', reduzido:'8005', nivel:'9', descricao:'ICMS a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112420000', unidade: '1', reduzido:'1181', nivel:'9', descricao:'IPI a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112430000', unidade: '1', reduzido:'7886', nivel:'9', descricao:'IRRF a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112440000', unidade: '1', reduzido:'9593', nivel:'9', descricao:'CSLL a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112450000', unidade: '1', reduzido:'9901', nivel:'9', descricao:'PIS a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112460000', unidade: '1', reduzido:'9206', nivel:'9', descricao:'INSS a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112470000', unidade: '1', reduzido:'8582', nivel:'9', descricao:'COFINS a recuperar' })
    handleInclusao(apiURLcontas,{ estrutural: '112480000', unidade: '1', reduzido:'9213', nivel:'9', descricao:'Outros tributos a recuperar' }      )
    handleInclusao(apiURLcontas,{ estrutural: '113000000', unidade: '1', reduzido:'5295', nivel:'3', descricao:'ESTOQUES' })
    handleInclusao(apiURLcontas,{ estrutural: '113100000', unidade: '1', reduzido:'9108', nivel:'4', descricao:'Mercadorias' } )
    handleInclusao(apiURLcontas,{ estrutural: '113110000', unidade: '1', reduzido:'7730', nivel:'9', descricao:'Mercadorias para Revenda' }        )
    handleInclusao(apiURLcontas,{ estrutural: '113200000', unidade: '1', reduzido:'3272', nivel:'4', descricao:'Produtos' })
    handleInclusao(apiURLcontas,{ estrutural: '113210000', unidade: '1', reduzido:'1598', nivel:'9', descricao:'Produtos acabados' }   )
    handleInclusao(apiURLcontas,{ estrutural: '113220000', unidade: '1', reduzido:'1724', nivel:'9', descricao:'Produtos em elaboração' }     )
    handleInclusao(apiURLcontas,{ estrutural: '113230000', unidade: '1', reduzido:'2012', nivel:'9', descricao:'Matéria prima' })
    handleInclusao(apiURLcontas,{ estrutural: '113300000', unidade: '1', reduzido:'1193', nivel:'4', descricao:'Outros Custos' })
    handleInclusao(apiURLcontas,{ estrutural: '113310000', unidade: '1', reduzido:'8367', nivel:'9', descricao:'Importação em andamento' }    )
    handleInclusao(apiURLcontas,{ estrutural: '113320000', unidade: '1', reduzido:'4804', nivel:'9', descricao:'Adiantamento a fornecedores' }     )
    handleInclusao(apiURLcontas,{ estrutural: '113330000', unidade: '1', reduzido:'3863', nivel:'9', descricao:'(-) Perdas estimadas para redução ao valor recuperável' })
    handleInclusao(apiURLcontas,{ estrutural: '114000000', unidade: '1', reduzido:'5986', nivel:'3', descricao:'ATIVOS ESPECIAIS' })
    handleInclusao(apiURLcontas,{ estrutural: '114100000', unidade: '1', reduzido:'9139', nivel:'4', descricao:'Ativos especiais' })
    handleInclusao(apiURLcontas,{ estrutural: '114110000', unidade: '1', reduzido:'5591', nivel:'9', descricao:'Ativos especiais em produção' }      )
    handleInclusao(apiURLcontas,{ estrutural: '114120000', unidade: '1', reduzido:'1706', nivel:'9', descricao:'(-) Amortização acumulada' })
    handleInclusao(apiURLcontas,{ estrutural: '114130000', unidade: '1', reduzido:'4741', nivel:'9', descricao:'(-) Perdas estimadas para redução ao valor recuperável' })
    handleInclusao(apiURLcontas,{ estrutural: '115000000', unidade: '1', reduzido:'5990', nivel:'3', descricao:'DESPESAS DO EXERCÍCIO SEGUINTE PAGAS ANTECIPADAMENTE' })
    handleInclusao(apiURLcontas,{ estrutural: '115100000', unidade: '1', reduzido:'1020', nivel:'4', descricao:'Despesas antecipadas' })
    handleInclusao(apiURLcontas,{ estrutural: '115110000', unidade: '1', reduzido:'7689', nivel:'9', descricao:'Prêmios de seguros a apropriar' }    )
    handleInclusao(apiURLcontas,{ estrutural: '115120000', unidade: '1', reduzido:'4576', nivel:'9', descricao:'Encargos financeiros a apropriar' }   )
    handleInclusao(apiURLcontas,{ estrutural: '115130000', unidade: '1', reduzido:'1570', nivel:'9', descricao:'Assinaturas e anuidades a apropriar' }   )
    handleInclusao(apiURLcontas,{ estrutural: '120000000', unidade: '1', reduzido:'4644', nivel:'2', descricao:'ATIVO NÃO CIRCULANTE' })
    handleInclusao(apiURLcontas,{ estrutural: '121000000', unidade: '1', reduzido:'2308', nivel:'3', descricao:'REALIZÁVEL A LONGO PRAZO' }  )
    handleInclusao(apiURLcontas,{ estrutural: '121100000', unidade: '1', reduzido:'4720', nivel:'4', descricao:'Créditos' })
    handleInclusao(apiURLcontas,{ estrutural: '121110000', unidade: '1', reduzido:'3531', nivel:'9', descricao:'Adiantamento a terceiros' }          )
    handleInclusao(apiURLcontas,{ estrutural: '121120000', unidade: '1', reduzido:'3595', nivel:'9', descricao:'(-) Ajuste a valor presente' }          )
    handleInclusao(apiURLcontas,{ estrutural: '121200000', unidade: '1', reduzido:'9278', nivel:'4', descricao:'Tributos Diferidos' } )
    handleInclusao(apiURLcontas,{ estrutural: '121210000', unidade: '1', reduzido:'8365', nivel:'9', descricao:'IRPJ Diferido' })
    handleInclusao(apiURLcontas,{ estrutural: '121220000', unidade: '1', reduzido:'8651', nivel:'9', descricao:'CSLL Diferida' })
    handleInclusao(apiURLcontas,{ estrutural: '122000000', unidade: '1', reduzido:'5790', nivel:'3', descricao:'INVESTIMENTOS' })
    handleInclusao(apiURLcontas,{ estrutural: '122100000', unidade: '1', reduzido:'9199', nivel:'4', descricao:'Participações Permanentes em Outras Sociedades' })
    handleInclusao(apiURLcontas,{ estrutural: '122110000', unidade: '1', reduzido:'6216', nivel:'9', descricao:'Avaliadas pela equivalência patrimonial' })
    handleInclusao(apiURLcontas,{ estrutural: '122120000', unidade: '1', reduzido:'5875', nivel:'9', descricao:'Avaliadas pelo custo' })
    handleInclusao(apiURLcontas,{ estrutural: '122200000', unidade: '1', reduzido:'6027', nivel:'4', descricao:'Propriedades para Investimento' }          )
    handleInclusao(apiURLcontas,{ estrutural: '122210000', unidade: '1', reduzido:'1160', nivel:'9', descricao:'Propriedades para investimento' }    )
    handleInclusao(apiURLcontas,{ estrutural: '122300000', unidade: '1', reduzido:'1191', nivel:'4', descricao:'Outros Investimentos Permanentes' }      )
    handleInclusao(apiURLcontas,{ estrutural: '122310000', unidade: '1', reduzido:'3551', nivel:'9', descricao:'Obras de arte' })
    handleInclusao(apiURLcontas,{ estrutural: '123000000', unidade: '1', reduzido:'3992', nivel:'3', descricao:'IMOBILIZADO' })
    handleInclusao(apiURLcontas,{ estrutural: '123100000', unidade: '1', reduzido:'4490', nivel:'4', descricao:'Bens em Operação' }   )
    handleInclusao(apiURLcontas,{ estrutural: '123110000', unidade: '1', reduzido:'6107', nivel:'9', descricao:'Terrenos' })
    handleInclusao(apiURLcontas,{ estrutural: '123120000', unidade: '1', reduzido:'3864', nivel:'9', descricao:'Obras civis' })
    handleInclusao(apiURLcontas,{ estrutural: '123130000', unidade: '1', reduzido:'1558', nivel:'9', descricao:'Instalações' })
    handleInclusao(apiURLcontas,{ estrutural: '123140000', unidade: '1', reduzido:'9074', nivel:'9', descricao:'Máquinas, equipamentos e ferramentas' })
    handleInclusao(apiURLcontas,{ estrutural: '123150000', unidade: '1', reduzido:'2833', nivel:'9', descricao:'Móveis e utensílios' })
    handleInclusao(apiURLcontas,{ estrutural: '123160000', unidade: '1', reduzido:'1375', nivel:'9', descricao:'Computadores e periféricos' }    )
    handleInclusao(apiURLcontas,{ estrutural: '123170000', unidade: '1', reduzido:'4240', nivel:'9', descricao:'Veículos' })
    handleInclusao(apiURLcontas,{ estrutural: '123180000', unidade: '1', reduzido:'9876', nivel:'9', descricao:'Ferramentas' })
    handleInclusao(apiURLcontas,{ estrutural: '123190000', unidade: '1', reduzido:'5152', nivel:'9', descricao:'Florestamento e reflorestamento' })
    handleInclusao(apiURLcontas,{ estrutural: '123110000', unidade: '1', reduzido:'7946', nivel:'9', descricao:'Benfeitorias em propriedades de terceiros' })
    handleInclusao(apiURLcontas,{ estrutural: '123200000', unidade: '1', reduzido:'7493', nivel:'4', descricao:'(-) Depreciação, Amortização e Exaustão Acumulada e Perdas por Redução ao Valor Recuperável' })
    handleInclusao(apiURLcontas,{ estrutural: '123210000', unidade: '1', reduzido:'7766', nivel:'9', descricao:'Terrenos' })
    handleInclusao(apiURLcontas,{ estrutural: '123220000', unidade: '1', reduzido:'2758', nivel:'9', descricao:'Obras civis' })
    handleInclusao(apiURLcontas,{ estrutural: '123230000', unidade: '1', reduzido:'8097', nivel:'9', descricao:'Instalações' })
    handleInclusao(apiURLcontas,{ estrutural: '123240000', unidade: '1', reduzido:'8678', nivel:'9', descricao:'Máquinas, equipamentos e ferramentas' })
    handleInclusao(apiURLcontas,{ estrutural: '123250000', unidade: '1', reduzido:'2774', nivel:'9', descricao:'Móveis e utensílios' })
    handleInclusao(apiURLcontas,{ estrutural: '123260000', unidade: '1', reduzido:'2570', nivel:'9', descricao:'Computadores e periféricos' }    )
    handleInclusao(apiURLcontas,{ estrutural: '123270000', unidade: '1', reduzido:'2256', nivel:'9', descricao:'Veículos' })
    handleInclusao(apiURLcontas,{ estrutural: '123280000', unidade: '1', reduzido:'6056', nivel:'9', descricao:'Ferramentas' })
    handleInclusao(apiURLcontas,{ estrutural: '123290000', unidade: '1', reduzido:'6115', nivel:'9', descricao:'Florestamento e reflorestamento' })
    handleInclusao(apiURLcontas,{ estrutural: '123210000', unidade: '1', reduzido:'2341', nivel:'5', descricao:'Benfeitorias em propriedades de terceiros' }       )
    handleInclusao(apiURLcontas,{ estrutural: '123211000', unidade: '1', reduzido:'3823', nivel:'9', descricao:'Perdas estimadas por redução ao valore recuperável' })
    handleInclusao(apiURLcontas,{ estrutural: '123300000', unidade: '1', reduzido:'9041', nivel:'4', descricao:'Imobilizado Arrendado' })
    handleInclusao(apiURLcontas,{ estrutural: '123310000', unidade: '1', reduzido:'1439', nivel:'9', descricao:'Veículos arrendados' })
    handleInclusao(apiURLcontas,{ estrutural: '123320000', unidade: '1', reduzido:'3523', nivel:'9', descricao:'Máquinas arrendadas' })
    handleInclusao(apiURLcontas,{ estrutural: '123400000', unidade: '1', reduzido:'4651', nivel:'4', descricao:'(-) Depreciação Acumulada de Bens Arrendados' })
    handleInclusao(apiURLcontas,{ estrutural: '123410000', unidade: '1', reduzido:'3280', nivel:'9', descricao:'Veículos arrendados' })
    handleInclusao(apiURLcontas,{ estrutural: '123420000', unidade: '1', reduzido:'5698', nivel:'9', descricao:'Máquinas arrendadas' })
    handleInclusao(apiURLcontas,{ estrutural: '123500000', unidade: '1', reduzido:'8222', nivel:'4', descricao:'Imobilizado em Andamento' }     )
    handleInclusao(apiURLcontas,{ estrutural: '123510000', unidade: '1', reduzido:'9250', nivel:'9', descricao:'Construção em andamento' })
    handleInclusao(apiURLcontas,{ estrutural: '123520000', unidade: '1', reduzido:'4908', nivel:'9', descricao:'Importação de bens do imobilizado em andamento' })
    handleInclusao(apiURLcontas,{ estrutural: '123530000', unidade: '1', reduzido:'2023', nivel:'9', descricao:'Adiantamento a fornecedores de imobilizado' })
    handleInclusao(apiURLcontas,{ estrutural: '124000000', unidade: '1', reduzido:'9882', nivel:'3', descricao:'INTANGÍVEL' })
    handleInclusao(apiURLcontas,{ estrutural: '124100000', unidade: '1', reduzido:'8380', nivel:'4', descricao:'Custo' })
    handleInclusao(apiURLcontas,{ estrutural: '124110000', unidade: '1', reduzido:'6865', nivel:'9', descricao:'Marcas' })
    handleInclusao(apiURLcontas,{ estrutural: '124120000', unidade: '1', reduzido:'7803', nivel:'9', descricao:'Patentes' })
    handleInclusao(apiURLcontas,{ estrutural: '124130000', unidade: '1', reduzido:'8652', nivel:'9', descricao:'Concessões' })
    handleInclusao(apiURLcontas,{ estrutural: '124140000', unidade: '1', reduzido:'7108', nivel:'9', descricao:'Agio (good will)' }   )
    handleInclusao(apiURLcontas,{ estrutural: '124160000', unidade: '1', reduzido:'9649', nivel:'9', descricao:'Direitos autorais' } )
    handleInclusao(apiURLcontas,{ estrutural: '124200000', unidade: '1', reduzido:'1591', nivel:'4', descricao:'(-) Amortização Acumulada e Perdas por Redução ao Valor Recuperável' })
    handleInclusao(apiURLcontas,{ estrutural: '124210000', unidade: '1', reduzido:'1542', nivel:'9', descricao:'Marcas' })
    handleInclusao(apiURLcontas,{ estrutural: '124220000', unidade: '1', reduzido:'8505', nivel:'9', descricao:'Patentes' })
    handleInclusao(apiURLcontas,{ estrutural: '124230000', unidade: '1', reduzido:'5338', nivel:'9', descricao:'Concessões' })
    handleInclusao(apiURLcontas,{ estrutural: '124240000', unidade: '1', reduzido:'8291', nivel:'9', descricao:'Agio (good will)' }   )
    handleInclusao(apiURLcontas,{ estrutural: '124260000', unidade: '1', reduzido:'7771', nivel:'9', descricao:'Direitos autorais' } )
    handleInclusao(apiURLcontas,{ estrutural: '200000000', unidade: '1', reduzido:'4489', nivel:'1', descricao:'PASSIVO' })
    handleInclusao(apiURLcontas,{ estrutural: '210000000', unidade: '1', reduzido:'4524', nivel:'2', descricao:'PASSIVO CIRCULANTE' }         )
    handleInclusao(apiURLcontas,{ estrutural: '211000000', unidade: '1', reduzido:'6937', nivel:'3', descricao:'OBRIGAÇÕES DE CURTO PRAZO' }              )
    handleInclusao(apiURLcontas,{ estrutural: '211100000', unidade: '1', reduzido:'9297', nivel:'4', descricao:'Fornecedores' })
    handleInclusao(apiURLcontas,{ estrutural: '211110000', unidade: '1', reduzido:'2680', nivel:'9', descricao:'Fornecedores demonstração' }       )
    handleInclusao(apiURLcontas,{ estrutural: '211200000', unidade: '1', reduzido:'3093', nivel:'4', descricao:'Salários e Encargos Sociais' }         )
    handleInclusao(apiURLcontas,{ estrutural: '211210000', unidade: '1', reduzido:'3096', nivel:'9', descricao:'Salários a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211220000', unidade: '1', reduzido:'7924', nivel:'9', descricao:'13º a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211230000', unidade: '1', reduzido:'2980', nivel:'9', descricao:'Férias a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211240000', unidade: '1', reduzido:'2459', nivel:'9', descricao:'INSS a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211250000', unidade: '1', reduzido:'8900', nivel:'9', descricao:'FGTS a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211260000', unidade: '1', reduzido:'9490', nivel:'9', descricao:'IRRF a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211270000', unidade: '1', reduzido:'7681', nivel:'9', descricao:'Pró-labore a pagar' }   )
    handleInclusao(apiURLcontas,{ estrutural: '211300000', unidade: '1', reduzido:'9914', nivel:'4', descricao:'Obrigações Fiscais' }   )
    handleInclusao(apiURLcontas,{ estrutural: '211310000', unidade: '1', reduzido:'5862', nivel:'9', descricao:'ICMS a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211320000', unidade: '1', reduzido:'3001', nivel:'9', descricao:'IPI a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211330000', unidade: '1', reduzido:'4216', nivel:'9', descricao:'PIS / Pasep a pagar' }     )
    handleInclusao(apiURLcontas,{ estrutural: '211340000', unidade: '1', reduzido:'8371', nivel:'9', descricao:'Cofins a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211350000', unidade: '1', reduzido:'7441', nivel:'9', descricao:'ISS a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211360000', unidade: '1', reduzido:'9382', nivel:'9', descricao:'IRPJ a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211370000', unidade: '1', reduzido:'2029', nivel:'9', descricao:'CSLL a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211380000', unidade: '1', reduzido:'5928', nivel:'9', descricao:'Refis a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211390000', unidade: '1', reduzido:'5920', nivel:'9', descricao:'(-) Ajuste a valor presente' }           )
    handleInclusao(apiURLcontas,{ estrutural: '211400000', unidade: '1', reduzido:'3295', nivel:'4', descricao:'Empréstimos e Financiamentos' }            )
    handleInclusao(apiURLcontas,{ estrutural: '211410000', unidade: '1', reduzido:'7611', nivel:'9', descricao:'Empréstimos e financiamentos bancários de curto prazo' })
    handleInclusao(apiURLcontas,{ estrutural: '211420000', unidade: '1', reduzido:'9791', nivel:'9', descricao:'Duplicatas descontadas' })
    handleInclusao(apiURLcontas,{ estrutural: '211430000', unidade: '1', reduzido:'1971', nivel:'9', descricao:'Títulos a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211440000', unidade: '1', reduzido:'8786', nivel:'9', descricao:'(-) Juros a apropriar' }   )
    handleInclusao(apiURLcontas,{ estrutural: '211500000', unidade: '1', reduzido:'8831', nivel:'4', descricao:'Debêntures' })
    handleInclusao(apiURLcontas,{ estrutural: '211510000', unidade: '1', reduzido:'6939', nivel:'9', descricao:'Conversíveis em ações' }    )
    handleInclusao(apiURLcontas,{ estrutural: '211600000', unidade: '1', reduzido:'9721', nivel:'4', descricao:'Outras Obrigações Diversas' }         )
    handleInclusao(apiURLcontas,{ estrutural: '211610000', unidade: '1', reduzido:'9038', nivel:'9', descricao:'Adiantamento de clientes' } )
    handleInclusao(apiURLcontas,{ estrutural: '211620000', unidade: '1', reduzido:'5919', nivel:'9', descricao:'Contas a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '211630000', unidade: '1', reduzido:'5242', nivel:'9', descricao:'Comissões a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '220000000', unidade: '1', reduzido:'8670', nivel:'2', descricao:'PASSIVO NÃO CIRCULANTE' }   )
    handleInclusao(apiURLcontas,{ estrutural: '221000000', unidade: '1', reduzido:'3511', nivel:'3', descricao:'OBRIGAÇÕES DE LONGO PRAZO' }    )
    handleInclusao(apiURLcontas,{ estrutural: '221100000', unidade: '1', reduzido:'7606', nivel:'4', descricao:'Empréstimos e Financiamentos' }     )
    handleInclusao(apiURLcontas,{ estrutural: '221110000', unidade: '1', reduzido:'7457', nivel:'9', descricao:'Empréstimos e financiamentos bancários de longo prazo' })
    handleInclusao(apiURLcontas,{ estrutural: '221200000', unidade: '1', reduzido:'2239', nivel:'4', descricao:'Debêntures' })
    handleInclusao(apiURLcontas,{ estrutural: '221210000', unidade: '1', reduzido:'7225', nivel:'9', descricao:'Conversíveis em ações' }    )
    handleInclusao(apiURLcontas,{ estrutural: '221300000', unidade: '1', reduzido:'6631', nivel:'4', descricao:'Tributos Diferidos' } )
    handleInclusao(apiURLcontas,{ estrutural: '221310000', unidade: '1', reduzido:'6112', nivel:'9', descricao:'IRPJ Diferido' })
    handleInclusao(apiURLcontas,{ estrutural: '221320000', unidade: '1', reduzido:'4924', nivel:'9', descricao:'CSLL Diferida' })
    handleInclusao(apiURLcontas,{ estrutural: '221400000', unidade: '1', reduzido:'9590', nivel:'4', descricao:'Parcelamentos' })
    handleInclusao(apiURLcontas,{ estrutural: '221410000', unidade: '1', reduzido:'1931', nivel:'9', descricao:'Refis a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '221420000', unidade: '1', reduzido:'3125', nivel:'9', descricao:'Paes a pagar' })
    handleInclusao(apiURLcontas,{ estrutural: '221430000', unidade: '1', reduzido:'9060', nivel:'9', descricao:'(-) Ajuste a valor presente' }            )
    handleInclusao(apiURLcontas,{ estrutural: '221500000', unidade: '1', reduzido:'8977', nivel:'4', descricao:'Provisões' })
    handleInclusao(apiURLcontas,{ estrutural: '221510000', unidade: '1', reduzido:'3870', nivel:'9', descricao:'Provisões para garantias' }         )
    handleInclusao(apiURLcontas,{ estrutural: '221520000', unidade: '1', reduzido:'1705', nivel:'9', descricao:'Provisões fiscais' })
    handleInclusao(apiURLcontas,{ estrutural: '230000000', unidade: '1', reduzido:'3904', nivel:'2', descricao:'PATRIMÔNIO LÍQUIDO' })
    handleInclusao(apiURLcontas,{ estrutural: '231000000', unidade: '1', reduzido:'6759', nivel:'3', descricao:'PATRIMÔNIO LÍQUIDO DOS SÓCIOS' }         )
    handleInclusao(apiURLcontas,{ estrutural: '231100000', unidade: '1', reduzido:'2802', nivel:'4', descricao:'Capital Social' })
    handleInclusao(apiURLcontas,{ estrutural: '231110000', unidade: '1', reduzido:'6080', nivel:'9', descricao:'Capital subscrito' })
    handleInclusao(apiURLcontas,{ estrutural: '231120000', unidade: '1', reduzido:'3676', nivel:'9', descricao:'(-) capital a integralizar' }      )
    handleInclusao(apiURLcontas,{ estrutural: '231200000', unidade: '1', reduzido:'8160', nivel:'4', descricao:'Reserva de Capital' })
    handleInclusao(apiURLcontas,{ estrutural: '231210000', unidade: '1', reduzido:'4515', nivel:'9', descricao:'Agio na emissão de ações' })
    handleInclusao(apiURLcontas,{ estrutural: '231300000', unidade: '1', reduzido:'2855', nivel:'4', descricao:'Opções Outorgadas Reconhecidas' }      )
    handleInclusao(apiURLcontas,{ estrutural: '231310000', unidade: '1', reduzido:'4750', nivel:'9', descricao:'Opções Outorgadas Reconhecidas' })
    handleInclusao(apiURLcontas,{ estrutural: '231400000', unidade: '1', reduzido:'4479', nivel:'4', descricao:'Reserva de Reavaliação - Saldos até 31/12/27' })
    handleInclusao(apiURLcontas,{ estrutural: '231410000', unidade: '1', reduzido:'8523', nivel:'9', descricao:'Reavaliação de imobilizado' })
    handleInclusao(apiURLcontas,{ estrutural: '231500000', unidade: '1', reduzido:'4866', nivel:'4', descricao:'Ajuste de Avaliação Patrimonial' }     )
    handleInclusao(apiURLcontas,{ estrutural: '231510000', unidade: '1', reduzido:'9841', nivel:'9', descricao:'Custo atribuído Imobilizado - ICPC 1' })
    handleInclusao(apiURLcontas,{ estrutural: '231600000', unidade: '1', reduzido:'6604', nivel:'4', descricao:'Reserva de Lucros' })
    handleInclusao(apiURLcontas,{ estrutural: '231610000', unidade: '1', reduzido:'6587', nivel:'9', descricao:'Reserva Legal' })
    handleInclusao(apiURLcontas,{ estrutural: '231620000', unidade: '1', reduzido:'4423', nivel:'9', descricao:'Reserva Estatutária' }   )
    handleInclusao(apiURLcontas,{ estrutural: '231630000', unidade: '1', reduzido:'8833', nivel:'9', descricao:'Reserva para Contingências' }       )
    handleInclusao(apiURLcontas,{ estrutural: '231640000', unidade: '1', reduzido:'1608', nivel:'9', descricao:'Reserva de lucros a realizar' }      )
    handleInclusao(apiURLcontas,{ estrutural: '231650000', unidade: '1', reduzido:'5658', nivel:'9', descricao:'Reserva de lucros para expansão' }      )
    handleInclusao(apiURLcontas,{ estrutural: '231660000', unidade: '1', reduzido:'4294', nivel:'9', descricao:'Reserva Especial para Dividendos Obrigatórios Não Distribuídos' })
    handleInclusao(apiURLcontas,{ estrutural: '231670000', unidade: '1', reduzido:'9244', nivel:'9', descricao:'Reserva de Incentivos Fiscais' })
    handleInclusao(apiURLcontas,{ estrutural: '231700000', unidade: '1', reduzido:'2121', nivel:'4', descricao:'(-) Ações em Tesouraria' })
    handleInclusao(apiURLcontas,{ estrutural: '231710000', unidade: '1', reduzido:'2910', nivel:'9', descricao:'Ações em  tesouraria' })
    handleInclusao(apiURLcontas,{ estrutural: '231800000', unidade: '1', reduzido:'1788', nivel:'4', descricao:'Ajuste Acumulado de Conversão' }         )
    handleInclusao(apiURLcontas,{ estrutural: '231810000', unidade: '1', reduzido:'1631', nivel:'9', descricao:'Ajuste Acumulado de Conversão' }   )
    handleInclusao(apiURLcontas,{ estrutural: '231900000', unidade: '1', reduzido:'4172', nivel:'4', descricao:'Lucro ou Prejuízos Acumulados' }   )
    handleInclusao(apiURLcontas,{ estrutural: '231910000', unidade: '1', reduzido:'9187', nivel:'9', descricao:'Lucro acumulados' })
    handleInclusao(apiURLcontas,{ estrutural: '231920000', unidade: '1', reduzido:'2896', nivel:'9', descricao:'(-) Prejuízos acumulados' }     )
    handleInclusao(apiURLcontas,{ estrutural: '231100000', unidade: '1', reduzido:'1994', nivel:'4', descricao:'Participação de Acionistas não Controladores (só no Balanço Consolidado)' })
    handleInclusao(apiURLcontas,{ estrutural: '231110000', unidade: '1', reduzido:'5725', nivel:'9', descricao:'Participação de Acionistas não controladores' })

    handleInclusao(apiURLlancamentos, { codigo: 56, data: "20221120", valor: 104.50, historico: 1, complemento: "",                   contaCredito: "231910000", contaDebito: "231710000", unidade: "1" } )
    handleInclusao(apiURLlancamentos, { codigo: 57, data: "20221005", valor: 251.50, historico: 5, complemento: "878.345 - Domênico", contaCredito: "231910000", contaDebito: "231710000", unidade: "1" } )
    handleInclusao(apiURLlancamentos, { codigo: 58, data: "20221114", valor: 314.75, historico: 3, complemento: "345 - Juarez",       contaCredito: "231910000", contaDebito: "231710000", unidade: "1" } )
    handleInclusao(apiURLlancamentos, { codigo: 59, data: "20220901", valor: 491.00, historico: 1, complemento: "Roberto",            contaCredito: "231910000", contaDebito: "231710000", unidade: "1" } )
    handleInclusao(apiURLlancamentos, { codigo: 60, data: "20221105", valor:   1.50, historico: 2, complemento: "",                   contaCredito: "231910000", contaDebito: "231710000", unidade: "1" } )

    handleInclusao(apiURLsdAno,{ estrutural: '231110000', unidade: '1', saldo: 0, ano: 0 })
    handleInclusao(apiURLsdMes,{ estrutural: '231110000', unidade: '1', saldo: 0, ano: 0, mes: 0 })
    handleInclusao(apiURLsdDia,{ estrutural: '231110000', unidade: '1', saldo: 0, ano: 0, mes: 0, dia: 0 })

    return (
        <div>

        passou por aqui...

        </div>
    )
}

export default BaseDados

